export const COMPANY_DETAILS = {
  name: "Tutvex",
  legalName: "Tutvex Education Technologies Pvt. Ltd.",
  tagline: "Prayagraj's #1 Verified Home Tuition & Personal Tutor Platform",
  phone: "+91 9330275932",
  whatsapp: "+91 9305275932",
  email: "support@tutvex.com",
  officeAddress: "Serving Prayagraj (Allahabad), Uttar Pradesh",
  gbpLink: "https://share.google/S33LPeNKRG5whFEke",
  cidLink: "https://www.google.com/maps?cid=7024959596788940233",
  mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d230660.86914568208!2d81.66150881640627!3d25.4022638!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x862286d3776211db%3A0x617dab8890137dc9!2sTutvex%20%E2%80%93%20Home%20Tuition%20Provider%2C%20Prayagraj!5e0!3m2!1sen!2sin!4v1784877450430!5m2!1sen!2sin",
  ratingValue: "4.9",
  reviewCount: "542",
  operatingHours: "Mo-Su 07:00-21:00",
};

export const ALLAHABAD_LOCATIONS = [
  "Civil Lines",
  "Katra",
  "George Town",
  "Tagore Town",
  "Elgin Road",
  "Thornhill Road",
  "Lukerganj",
  "Leader Road",
  "Zero Road",
  "Johnstonganj",
  "Mutthiganj",
  "Attarsuiya",
  "Chowk",
  "Dhoomanganj",
  "Khuldabad",
  "Rambagh",
  "Bahadurganj",
  "Nakhaskona",
  "Meerganj",
  "Shahganj",
  "Daraganj",
  "Kydganj",
  "Rajapur",
  "Alopibagh",
  "Minto Park",
  "Teliarganj",
  "Old Katra",
  "New Katra",
  "Beli Gaon",
  "Ashok Nagar",
  "Naini",
  "ADA Colony",
  "Trivenipuram",
  "Mahewa",
  "Karchana",
  "Shantipuram",
  "Jhusi",
  "Jhusi Kohna",
  "Jhusi Railway Colony",
  "Phaphamau",
  "Andawa",
  "Handia",
  "Bamrauli",
  "Bamrauli Airport Area",
  "Dandi",
  "Sulem Sarai",
  "Soraon",
  "Sikandra",
  "Sadiyabad",
  "Sarai Inayat",
  "Koraon",
  "Utraon",
  "Meja",
  "Nawabganj",
  "Preetam Nagar",
  "Rajrooppur",
  "Govindpur",
  "Shivkuti",
  "Beli Road Colony",
  "Sangam Vihar",
  "Kalyani Devi",
];

export const INTENTS = {
  needTutor: [
    "home tutor",
    "home tuition",
    "private tutor",
    "personal tutor",
    "tutor near me",
    "tuition teacher",
    "home teacher",
    "private tuition",
    "1 to 1 tuition",
    "one to one tuition",
    "best tutor",
    "verified tutor",
    "experienced tutor",
    "top tutor",
    "local tutor",
    "maths tutor",
    "math tutor",
    "physics tutor",
    "chemistry tutor",
    "biology tutor",
    "science tutor",
    "english tutor",
    "class 6 tutor",
    "class 7 tutor",
    "class 8 tutor",
    "class 9 tutor",
    "class 10 tutor",
    "class 11 tutor",
    "class 12 tutor",
    "board exam tutor",
    "cbse tutor",
    "icse tutor",
    "jee tutor",
    "neet tutor",
    "competitive exam tutor",
    "exam preparation tutor",
  ],
  becomeTutor: [
    "become tutor",
    "become home tutor",
    "tutor job",
    "home tutor job",
    "private tutor job",
    "tuition teacher job",
    "teaching job",
    "part time tutor",
    "part time teaching job",
    "online tutor job",
    "offline tutor job",
    "home tuition vacancy",
    "private tutor vacancy",
    "tutor requirement",
    "teacher requirement",
    "earn by teaching",
  ],
  general: [
    "best tuition",
    "top tuition",
    "verified tutors",
    "trusted tutor",
    "experienced teacher",
    "local tuition center",
    "tuition classes",
    "coaching near me",
    "study help",
    "academic help",
  ],
};

export const SUBJECTS = [
  "Maths",
  "Physics",
  "Chemistry",
  "Biology",
  "Science",
  "English",
  "Hindi",
  "Social Science",
  "History",
  "Geography",
  "Civics",
  "Economics",
  "Accountancy",
  "Business Studies",
  "Computer Science",
  "Information Technology",
  "Coding",
  "Python",
  "Java",
  "C++",
  "JEE Main",
  "JEE Advanced",
  "NEET",
  "CUET",
  "Olympiad",
  "NTSE",
  "Sanskrit",
  "French",
  "EVS",
  "GK",
  "CBSE",
  "ICSE",
  "ISC",
  "UP Board",
  "Spoken English",
];

export const POPULAR_CLASSES = [
  "Class 1 - 5 (Primary)",
  "Class 6 - 8 (Middle)",
  "Class 9 & 10 (Secondary)",
  "Class 11 & 12 (Higher Secondary)",
  "IIT-JEE / NEET Foundation",
  "UP Board Class 10 & 12 Special",
];
